apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricas-deploy
spec:
  selector:
    matchLabels:
      app: metricas-backend
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: metricas-backend
    spec:
      containers:
      - name: metricas-backend
        image: osmer15/app-prometheus:1
        ports:
        - containerPort: 3002
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1