apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-init
  labels:
      app: deployment-init
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-pod
  template: 
    metadata:
      labels: 
        app: my-pod         
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: install
        image: busybox:1.28
        command: ["wget","-O","/work-dir/index.html","https://checkip.amazonaws.com"]
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      volumes:
      - name: workdir
        emptyDir: {}