apiVersion: v1
kind: Service
metadata:
  name: svc-metricas
  labels:
    app: metricas-backend
spec:
  type: LoadBalancer  # Cambiado de LoadBalancer a ClusterIP
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  selector:
    app: metricas-backend