apiVersion: v1
kind: Service
metadata:
  name: svc-back
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: hello-backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8000
    
  selector:
    app: hello-backend