apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # Aqui especificamos el tipop de balanceador
spec:
  type: LoadBalancer
  selector:
    app: my-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80