apiVersion: v1
kind: Service
metadata:
  name: svc-metricas
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: metricas-backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP 
      port: 3002
      targetPort: 3002
    
  selector:
    app: metricas-backend