apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-container
          image: prom/prometheus:v2.34.0  # Usando imagen oficial de Prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml  # Esto asegura que solo el archivo prometheus.yml sea montado
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config  # Nombre del ConfigMap que contiene prometheus.yml
