apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'backend'
      scrape_interval: 15s
      metrics_path: /metrics
      static_configs:
      - targets: ['back-pod:80']
