apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-stful
spec:
  serviceName: "myapp"
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx  # Puedes cambiar a la imagen que desees
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config   # Monta el ConfigMap en este directorio
      volumes:
      - name: config-volume
        configMap:
          name: my-config          # Hace referencia al ConfigMap creado
